### ISSUE TITLE
Profanity on macOS via Homebrew doesn't support python plugins

### ISSUE THREAD

**Issue by pfannie** [profanity-im/profanity-plugins#10]
Hello everyone!

I installed Profanity using these steps: http://www.profanity.im/install.html#os-x, with terminal notifier but without pgp support: `brew install profanity --with-terminal-notifier --without-gpgme`.

Unfortunately, running `profanity -v` shows that python plugins are disabled.

```bash
Profanity, version 0.6.0dev.master.b768c8b
Copyright (C) 2012 - 2017 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled
PGP support: Disabled
C plugins: Enabled
Python plugins: Disabled
GTK icons: Disabled
```

What do I have to do to enable python plugins?

**Comment by boothj5** [comment]
The [brew formula](https://github.com/Homebrew/homebrew-core/blob/cf5c06f79277e518c2cc966afe450726e614287b/Formula/profanity.rb) currently has python plugin support disabled.

I'd suggest raising an issue at the homebrew project, for python plugin support the `python-dev` package is also a required dependency.

**Comment by pfannie** [comment]
I changed the formula and took out the line `"--disable-python-plugins",`. There was no problem installing it and I could use python plugins.

**Comment by pfannie** [comment]
Now I did actually find a problem, but I am not sure whether this is a problem with homebrew or with profanity. When I installed profanity through homebrew with python plugins enabled, for some reason profanity is using the system python version, which is not even in the PATH.

This is the part of the config.log:
```
configure:12411: Symlinking Python.framework to /Library/Frameworks/Python.framework
configure:12418: checking for python-config
configure:12434: found /usr/bin/python-config
configure:12446: result: yes
configure:12463: checking for python
configure:12481: found /usr/bin/python
configure:12493: result: /usr/bin/python
configure:12509: checking for a version of Python >= '2.1.0'
configure:12535: result: yes
configure:12566: checking for the distutils Python package
configure:12570: result: yes
configure:12584: checking for Python include path
configure:12600: result: -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
configure:12607: checking for Python library path
configure:12684: result: -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib -lpython2.7
configure:12691: checking for Python site-packages path
configure:12697: result: /Library/Python/2.7/site-packages
configure:12704: checking python extra libraries
configure:12711: result: -ldl  -framework CoreFoundation 
configure:12718: checking python extra linking flags
configure:12725: result: -u _PyMac_Error /System/Library/Frameworks/Python.framework/Versions/2.7/Python
configure:12732: checking consistency of all components of python development environment
```

**Comment by rwasielewski** [comment]
Any progress in this issue?

**Comment by jubalh** [comment]
I don't own a Mac so I can't test this. You guys should switch to GNU/Linux ;)
No more strange "Use system X instead of brew X".

**Comment by H3rnand3zzz** [comment]
Looks like it got fixed. Issue resolved, I guess?

**Comment by jubalh** [comment]
Ok :)
