### ISSUE TITLE
Plugin request. Draw a line each time you switch away or lost focus from a window.

### ISSUE THREAD

**Issue by seamus-45** [profanity-im/profanity-plugins#12]
Hello, does we have all necessary events/functions for implementing like this through plugins?
This handy script exists for irssi for years: https://github.com/irssi/scripts.irssi.org/blob/master/scripts/trackbar.pl

**Comment by DebXWoody** [comment]
Trackbar has been implemented in 0.8.0 core. Can we close this issue?

**Comment by jubalh** [comment]
Done in https://github.com/profanity-im/profanity/issues/1238
