### ISSUE TITLE
Browser plugin is not working properly with OMEMO encrypted messages

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity-plugins#13]
If you perform `/browser` in an OMEMO encrypted chat the address https://conversations.im/omemo/ from the unencrypted body part will be opened.

**Comment by jubalh** [comment]
While it is true that Conversations sends:
```
<body>I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo</body>
```

If you have created a proper OMEMO session with your contact everything works as expected.

I tested as follows:
Have a regular OMEMO encrypted conversation with someone and then type `/browser`:
```
12:18 - PLUG: Verschlüsselt von Conversations  
12:18 - No links found from someone@something.net
```

I then asked him to send me a link:

```
12:20 - PLUG: https://github.com/profanity-im/profanity/issues/1070 
12:21 - Opening https://github.com/profanity-im/profanity/issues/1070 in browser
```

The `PLUG` was there for testing purposes.
The plugins already get the decrypted content of the message.
